storage:
  type: SQLite
  host: "localhost"
  port: 3306
  database: "glowduels"
  user: "root"
  password: "password"

arenas:
  default:
    world: "world"
    spawn1:
      x: 0.5
      y: 100.0
      z: -10.5
      yaw: 0.0
      pitch: 0.0
    spawn2:
      x: 0.5
      y: 100.0
      z: 10.5
      yaw: 180.0
      pitch: 0.0
